---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: embedded
      # Spring起動の度に投入するSQLファイル 外部キーの関係で以下の順序で投入する
      schema-locations:
        - classpath:db/ddl/admin_account.sql
        - classpath:db/ddl/quiz_status.sql
        - classpath:db/ddl/quiz.sql
        - classpath:db/ddl/answer.sql

      data-locations:
        - classpath:db/dml/admin_account-data.sql
        - classpath:db/dml/quiz-data.sql
        - classpath:db/dml/answer-data.sql
  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    web: debug
    org.seasar.doma.jdbc.UtilLoggingJdbcLogger: debug
    org.springframework.jdbc.datasource.init: debug

doma:
  dialect: h2

extension:
  # ID : root / pass : passwordでログイン可能
  salt: salt