name: Maven Test

on:
  push:
    # publishの方で maven Packageを動かしている関係でmaster/main以外にpushした場合にmavenTestを動かす
    branches:
      - '**'
      - '!master'
      - '!main'
  pull_request:
    # master/develop/main ブランチ向けのPRでmaven testを実行
    branches:
      - master
      - develop
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        # JDL 11 
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

      # テストソースの実行
    - name: mavenTest
      run: mvn test
